export const NOTE_CONTENT_CHANGED = "NOTE_CONTENT_CHANGED";

export const NOTE_CATEGORY_CHANGED = "NOTE_CATEGORY_CHANGED";

export const SAVE_NOTE_BUTTON_CLICKED = "SAVE_NOTE_BUTTON_CLICKED";

export const EDIT_NOTE_BUTTON_CLICKED = "EDIT_NOTE_BUTTON_CLICKED";

export const CANCEL_EDIT_NOTE_BUTTON_CLICKED =
  "CANCEL_EDIT_NOTE_BUTTON_CLICKED";

export const REMOVE_NOTE_BUTTON_CLICKED = "REMOVE_NOTE_BUTTON_CLICKED";

export const ARCHIVE_NOTE_BUTTON_CLICKED = "ARCHIVE_NOTE_BUTTON_CLICKED";

export const UNARCHIVE_NOTE_BUTTON_CLICKED = "UNARCHIVE_NOTE_BUTTON_CLICKED";
